import type { PlatformPreset, ThemePreset } from '@/types';

export const PLATFORM_PRESETS: PlatformPreset[] = [
  {
    id: 'macos-terminal',
    name: 'macOS Terminal',
    description: 'Classic macOS Terminal.app — SF Mono, traffic light buttons',
    config: {
      backgroundColor: '#ffffff',
      textColor: '#000000',
      fontFamily: "'SF Mono', 'Monaco', 'Menlo', monospace",
      fontSize: 13,
      borderRadius: 10,
      windowTitle: 'bash — terminal — 80×24',
      padding: 20,
      isDarkMode: false,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: '$',
      customPrompt: 'user@mac:~$',
    },
  },
  {
    id: 'windows-cmd',
    name: 'Windows Command Prompt',
    description: 'Classic CMD — Consolas, #1e1e1e title bar, no rounded corners',
    config: {
      backgroundColor: '#0c0c0c',
      textColor: '#cccccc',
      fontFamily: "'Consolas', 'Courier New', monospace",
      fontSize: 16,
      borderRadius: 0,
      windowTitle: 'Command Prompt',
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 15,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: '>',
      customPrompt: 'C:\\Users\\User>',
    },
  },
  {
    id: 'windows-powershell',
    name: 'Windows PowerShell',
    description: 'PowerShell — blue #012456, Consolas, same chrome as CMD',
    config: {
      backgroundColor: '#012456',
      textColor: '#eeedf0',
      fontFamily: "'Consolas', 'Courier New', monospace",
      fontSize: 14,
      borderRadius: 0,
      windowTitle: 'Windows PowerShell',
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 15,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: 'PS>',
      customPrompt: 'PS C:\\Users\\User>',
    },
  },
  {
    id: 'windows-terminal',
    name: 'Windows Terminal (Win11)',
    description: 'Windows 11 Terminal — acrylic title bar, rounded tabs, Cascadia Code',
    config: {
      backgroundColor: '#000000',
      textColor: '#d4d4d4',
      fontFamily: "'Cascadia Code', 'Consolas', 'Courier New', monospace",
      fontSize: 21,
      borderRadius: 0,
      windowTitle: 'Administrator: C:\\Windows\\system32',
      padding: 8,
      terminalWidth: 1488,
      terminalHeight: 752,
      lineHeight: 1.3,
      isDarkMode: true,
      shadowIntensity: 0,
      showWindowButtons: true,
      showWindowChrome: true,
    },
  },
  {
    id: 'ubuntu-terminal',
    name: 'Ubuntu Terminal (GNOME)',
    description: 'GNOME terminal — CSD header #2d2d2d, 46px, Adwaita buttons, Ubuntu Mono',
    config: {
      backgroundColor: '#300a24',
      textColor: '#ffffff',
      fontFamily: "'Ubuntu Mono', monospace",
      fontSize: 13,
      borderRadius: 6,
      windowTitle: 'user@ubuntu: ~',
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 15,
      showWindowButtons: false,
      showWindowChrome: true,
      promptStyle: '$',
      customPrompt: 'user@ubuntu:~$',
    },
  },
  {
    id: 'kali-terminal',
    name: 'Kali Linux Terminal',
    description: 'Kali — GNOME chrome, #000000 background, green text, Adwaita buttons',
    config: {
      backgroundColor: '#000000',
      textColor: '#00ff00',
      fontFamily: "'Monaco', 'JetBrains Mono', monospace",
      fontSize: 13,
      borderRadius: 4,
      windowTitle: 'root@kali: ~',
      padding: 14,
      isDarkMode: true,
      shadowIntensity: 10,
      showWindowButtons: false,
      showWindowChrome: true,
      promptStyle: '#',
      customPrompt: '┌──(kali㉿kali)-[~]\n└─$',
    },
  },
  {
    id: 'vscode-terminal',
    name: 'VS Code Integrated Terminal',
    description: 'VS Code panel — TERMINAL tab bar, Cascadia Code, no window chrome',
    config: {
      backgroundColor: '#1e1e1e',
      textColor: '#cccccc',
      fontFamily: "'Cascadia Code', 'Consolas', monospace",
      fontSize: 13,
      borderRadius: 0,
      windowTitle: 'bash — Visual Studio Code',
      padding: 12,
      isDarkMode: true,
      shadowIntensity: 5,
      showWindowButtons: false,
      showWindowChrome: true,
      promptStyle: '$',
      customPrompt: 'user@mac:~/project$',
    },
  },
  {
    id: 'iterm2',
    name: 'iTerm2',
    description: 'iTerm2 — macOS traffic lights + tab bar, Menlo font',
    config: {
      backgroundColor: '#000000',
      textColor: '#ffffff',
      fontFamily: "'Menlo', 'Monaco', 'JetBrains Mono', monospace",
      fontSize: 13,
      borderRadius: 8,
      windowTitle: 'iTerm2 — zsh',
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: '$',
      customPrompt: 'user@mac:~$',
    },
  },
  {
    id: 'custom',
    name: 'Custom Terminal',
    description: 'Start from scratch or save your own preset',
    config: {
      backgroundColor: '#1e1e2e',
      textColor: '#cdd6f4',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 14,
      borderRadius: 8,
      windowTitle: 'bash — 80×24',
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
    },
  },
];

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'github-readme',
    name: 'GitHub README',
    description: 'Clean light theme for README screenshots',
    config: {
      backgroundColor: '#ffffff',
      textColor: '#24292e',
      fontFamily: "'JetBrains Mono', 'SF Mono', monospace",
      fontSize: 13,
      borderRadius: 6,
      padding: 20,
      isDarkMode: false,
      shadowIntensity: 15,
      showWindowChrome: true,
      showWindowButtons: true,
      backgroundCanvasColor: '#ffffff',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon cyberpunk hacker theme',
    config: {
      backgroundColor: '#0a0a0a',
      textColor: '#00ff41',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 14,
      borderRadius: 4,
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 40,
      showWindowChrome: true,
      showWindowButtons: true,
      cursorColor: '#00ff41',
      cursorStyle: 'block',
    },
  },
  {
    id: 'minimal-macos',
    name: 'Minimal macOS',
    description: 'Clean minimal macOS style',
    config: {
      backgroundColor: '#f5f5f7',
      textColor: '#1d1d1f',
      fontFamily: "'SF Mono', 'Menlo', monospace",
      fontSize: 13,
      borderRadius: 12,
      padding: 24,
      isDarkMode: false,
      shadowIntensity: 20,
      showWindowChrome: true,
      showWindowButtons: true,
      backgroundCanvasColor: '#f5f5f7',
    },
  },
  {
    id: 'hacker',
    name: 'Hacker Theme',
    description: 'Classic green-on-black hacker terminal',
    config: {
      backgroundColor: '#000000',
      textColor: '#00ff00',
      fontFamily: "'Courier New', monospace",
      fontSize: 15,
      borderRadius: 0,
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 10,
      showWindowChrome: true,
      showWindowButtons: false,
      cursorColor: '#00ff00',
      cursorStyle: 'block',
    },
  },
  {
    id: 'windows-error',
    name: 'Windows Error Log',
    description: 'Blue screen error log style',
    config: {
      backgroundColor: '#000080',
      textColor: '#c0c0c0',
      fontFamily: "'Consolas', 'Courier New', monospace",
      fontSize: 14,
      borderRadius: 0,
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 10,
      showWindowChrome: false,
      showWindowButtons: false,
      cursorColor: '#c0c0c0',
      backgroundCanvasColor: '#000080',
    },
  },
];
