import type { PlatformPreset, ThemePreset, TerminalConfig } from '@/types';

export const PLATFORM_PRESETS: PlatformPreset[] = [
  {
    id: 'macos-terminal',
    name: 'macOS Terminal',
    description: 'Classic macOS Terminal.app with the default theme',
    config: {
      backgroundColor: '#1e1e2e',
      textColor: '#cdd6f4',
      fontFamily: "'SF Mono', 'Menlo', 'Monaco', 'JetBrains Mono', monospace",
      fontSize: 14,
      borderRadius: 10,
      windowTitle: 'bash — terminal — 80×24',
      padding: 24,
      isDarkMode: true,
      shadowIntensity: 30,
      showWindowButtons: true,
      showWindowChrome: true,
    },
  },
  {
    id: 'windows-cmd',
    name: 'Windows Command Prompt',
    description: 'Classic CMD with legacy colors',
    config: {
      backgroundColor: '#0c0c0c',
      textColor: '#cccccc',
      fontFamily: "'Cascadia Code', 'Consolas', 'Courier New', monospace",
      fontSize: 14,
      borderRadius: 0,
      windowTitle: 'Command Prompt',
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: '>',
      customPrompt: 'C:\\Users\\User>',
    },
  },
  {
    id: 'windows-powershell',
    name: 'Windows PowerShell',
    description: 'PowerShell with blue terminal theme',
    config: {
      backgroundColor: '#012456',
      textColor: '#f0f0f0',
      fontFamily: "'Cascadia Code', 'Consolas', 'JetBrains Mono', monospace",
      fontSize: 14,
      borderRadius: 0,
      windowTitle: 'Windows PowerShell',
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: 'PS>',
      customPrompt: 'PS C:\\Users\\User>',
    },
  },
  {
    id: 'windows-terminal',
    name: 'Windows Terminal (Windows 11)',
    description: 'Windows 11 Windows Terminal — Administrator CMD style',
    config: {
      backgroundColor: '#000000',
      textColor: '#d4d4d4',
      fontFamily: "'Cascadia Code', 'Consolas', 'Courier New', monospace",
      fontSize: 21,
      borderRadius: 0,
      windowTitle: 'Administrator: C:\\Windows\\s',
      padding: 8,
      terminalWidth: 1488,
      terminalHeight: 752,
      lineHeight: 1.3,
      isDarkMode: true,
      shadowIntensity: 0,
      showWindowButtons: true,
      showWindowChrome: true,
    },
  },
  {
    id: 'ubuntu-terminal',
    name: 'Ubuntu Terminal',
    description: 'Default Ubuntu terminal with purple theme',
    config: {
      backgroundColor: '#300a24',
      textColor: '#ffffff',
      fontFamily: "'Ubuntu Mono', 'JetBrains Mono', 'monospace'",
      fontSize: 14,
      borderRadius: 6,
      windowTitle: 'user@ubuntu: ~',
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: '$',
      customPrompt: 'user@ubuntu:~$',
    },
  },
  {
    id: 'kali-terminal',
    name: 'Kali Linux Terminal',
    description: 'Kali Linux dark terminal with red accents',
    config: {
      backgroundColor: '#1a1a2e',
      textColor: '#00ff00',
      fontFamily: "'Monaco', 'JetBrains Mono', 'monospace'",
      fontSize: 13,
      borderRadius: 4,
      windowTitle: 'root@kali: ~',
      padding: 14,
      isDarkMode: true,
      shadowIntensity: 15,
      showWindowButtons: true,
      showWindowChrome: true,
      promptStyle: '#',
      customPrompt: 'root@kali:~#',
    },
  },
  {
    id: 'vscode-terminal',
    name: 'VS Code Integrated Terminal',
    description: 'Visual Studio Code terminal panel style',
    config: {
      backgroundColor: '#1e1e1e',
      textColor: '#cccccc',
      fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
      fontSize: 13,
      borderRadius: 4,
      windowTitle: 'bash — Visual Studio Code',
      padding: 12,
      isDarkMode: true,
      shadowIntensity: 10,
      showWindowButtons: false,
      showWindowChrome: false,
    },
  },
  {
    id: 'iterm2',
    name: 'iTerm2',
    description: 'iTerm2 with the Dracula theme',
    config: {
      backgroundColor: '#282a36',
      textColor: '#f8f8f2',
      fontFamily: "'JetBrains Mono', 'Fira Code', 'Menlo', monospace",
      fontSize: 14,
      borderRadius: 8,
      windowTitle: 'iTerm2 — zsh',
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 25,
      showWindowButtons: true,
      showWindowChrome: true,
    },
  },
  {
    id: 'custom',
    name: 'Custom Terminal',
    description: 'Start from scratch or save your own preset',
    config: {
      backgroundColor: '#1e1e2e',
      textColor: '#cdd6f4',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 14,
      borderRadius: 8,
      windowTitle: 'bash — 80×24',
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 20,
      showWindowButtons: true,
      showWindowChrome: true,
    },
  },
];

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'github-readme',
    name: 'GitHub README',
    description: 'Clean light theme for README screenshots',
    config: {
      backgroundColor: '#ffffff',
      textColor: '#24292e',
      fontFamily: "'JetBrains Mono', 'SF Mono', monospace",
      fontSize: 13,
      borderRadius: 6,
      padding: 20,
      isDarkMode: false,
      shadowIntensity: 15,
      showWindowChrome: true,
      showWindowButtons: true,
      backgroundCanvasColor: '#ffffff',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon cyberpunk hacker theme',
    config: {
      backgroundColor: '#0a0a0a',
      textColor: '#00ff41',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 14,
      borderRadius: 4,
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 40,
      showWindowChrome: true,
      showWindowButtons: true,
      cursorColor: '#00ff41',
      cursorStyle: 'block',
    },
  },
  {
    id: 'minimal-macos',
    name: 'Minimal macOS',
    description: 'Clean minimal macOS style',
    config: {
      backgroundColor: '#f5f5f7',
      textColor: '#1d1d1f',
      fontFamily: "'SF Mono', 'Menlo', monospace",
      fontSize: 13,
      borderRadius: 12,
      padding: 24,
      isDarkMode: false,
      shadowIntensity: 20,
      showWindowChrome: true,
      showWindowButtons: true,
      backgroundCanvasColor: '#f5f5f7',
    },
  },
  {
    id: 'hacker',
    name: 'Hacker Theme',
    description: 'Classic green-on-black hacker terminal',
    config: {
      backgroundColor: '#000000',
      textColor: '#00ff00',
      fontFamily: "'Courier New', monospace",
      fontSize: 15,
      borderRadius: 0,
      padding: 16,
      isDarkMode: true,
      shadowIntensity: 10,
      showWindowChrome: true,
      showWindowButtons: false,
      cursorColor: '#00ff00',
      cursorStyle: 'block',
    },
  },
  {
    id: 'windows-error',
    name: 'Windows Error Log',
    description: 'Blue screen error log style',
    config: {
      backgroundColor: '#000080',
      textColor: '#c0c0c0',
      fontFamily: "'Consolas', 'Courier New', monospace",
      fontSize: 14,
      borderRadius: 0,
      padding: 20,
      isDarkMode: true,
      shadowIntensity: 10,
      showWindowChrome: false,
      showWindowButtons: false,
      cursorColor: '#c0c0c0',
      backgroundCanvasColor: '#000080',
    },
  },
];

export function applyPlatformPreset(presetId: string, config: TerminalConfig): TerminalConfig {
  const preset = PLATFORM_PRESETS.find(p => p.id === presetId);
  if (!preset) return config;
  return { ...config, ...preset.config, platform: preset.id };
}

export function applyThemePreset(presetId: string, config: TerminalConfig): TerminalConfig {
  const preset = THEME_PRESETS.find(p => p.id === presetId);
  if (!preset) return config;
  return { ...config, ...preset.config };
}
